output "db_instance_id" {
  description = "RDS DB instance identifier."
  value       = aws_db_instance.this.id
}

output "db_instance_arn" {
  description = "ARN of the RDS DB instance."
  value       = aws_db_instance.this.arn
}

output "db_instance_endpoint" {
  description = "RDS PostgreSQL endpoint."
  value       = aws_db_instance.this.endpoint
}

output "db_instance_address" {
  description = "RDS PostgreSQL hostname."
  value       = aws_db_instance.this.address
}

output "db_instance_port" {
  description = "RDS PostgreSQL port."
  value       = aws_db_instance.this.port
}

output "db_name" {
  description = "Application database name."
  value       = aws_db_instance.this.db_name
}

output "db_username" {
  description = "RDS master username."
  value       = aws_db_instance.this.username
  sensitive   = true
}

# NOTE: This output was missing from the original module even though
# root main.tf's `secrets` module wiring reads module.rds.db_master_password
# — another one of the "dependency errors". The password itself is
# generated here (random_password.db_master) and never leaves state except
# through this deliberately sensitive output, consumed only by the Secrets
# module to seed AWS Secrets Manager.
output "db_master_password" {
  description = "RDS master password generated by random_password. Sensitive — consumed only by the Secrets module."
  value       = random_password.db_master.result
  sensitive   = true
}

output "db_subnet_group_name" {
  description = "RDS DB subnet group name."
  value       = aws_db_subnet_group.this.name
}

output "rds_monitoring_role_arn" {
  description = "IAM role ARN used by RDS Enhanced Monitoring."
  value       = aws_iam_role.rds_monitoring.arn
}