variable "project_name" {
  description = "Project name used for Secrets Manager resource naming."
  type        = string
}

variable "environment" {
  description = "Deployment environment such as staging or production."
  type        = string
}

variable "db_host" {
  description = "RDS PostgreSQL hostname."
  type        = string
}

variable "db_port" {
  description = "RDS PostgreSQL port."
  type        = number
  default     = 5432
}

variable "db_name" {
  description = "PostgreSQL database name."
  type        = string
}

variable "db_username" {
  description = "PostgreSQL master username."
  type        = string
}

variable "db_password" {
  description = "PostgreSQL master password generated by the RDS module."
  type        = string
  sensitive   = true
}